name: ESLint

on: [pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
    - uses: LKP-RnD/purge-expired-artifacts-action@v4
      with:
       token: ${{ secrets.GITHUB_TOKEN }}
       repo_to_purge: "frontity/frontity"
       dry_run: "false"
    - uses: actions/checkout@v2
    - run: npm install
    - uses: bradennapier/eslint-plus-action@v3.4.2
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      with:
        issueSummaryType: full
        reportIgnoredFiles: true
