name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm install
      - run: npm run build
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      # - name: Get version
      #   id: get_version
      #   run: |
      #     echo ::set-output name=tag::$(grep '"version"' package.json | cut -d '"' -f 4 | head -n 1)
      # # place this action LAST
      # - uses: Drill4J/vee-table@0.0.0
      #   with:
      #     # leave everything "as-is"
      #     github-access-token: ${{ secrets.VEE_TABLE_TOKEN }}
      #     action-type: 'add-version'
      #     ledger-repo-url: 'https://github.com/Drill4J/vee-ledger'
      #     ledger-repo-owner: 'Drill4J'
      #     ledger-repo-name: 'vee-ledger'
      #     version-component-id: ${{ github.event.repository.name }}
      #     # leave everything "as-is"

      #     # steps.build_artifact is your step, where new version tag is created
      #     version-tag: ${{ steps.get_version.outputs.tag }} # Pass new version tag
